package neu.edu.entity;
// Generated Dec 10, 2017 12:49:06 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bids generated by hbm2java
 */
public class Bids implements java.io.Serializable {

	private Integer bidId;
	private ServiceDetail serviceDetail;
	private Startup startup;
	private int bidAmount;
	private String description;
	private Date timeRequired;
	private String status;
	private Set workTables = new HashSet(0);

	public Bids() {
	}

	public Bids(ServiceDetail serviceDetail, Startup startup, int bidAmount, String description, Date timeRequired,
			String status) {
		this.serviceDetail = serviceDetail;
		this.startup = startup;
		this.bidAmount = bidAmount;
		this.description = description;
		this.timeRequired = timeRequired;
		this.status = status;
	}

	public Bids(ServiceDetail serviceDetail, Startup startup, int bidAmount, String description, Date timeRequired,
			String status, Set workTables) {
		this.serviceDetail = serviceDetail;
		this.startup = startup;
		this.bidAmount = bidAmount;
		this.description = description;
		this.timeRequired = timeRequired;
		this.status = status;
		this.workTables = workTables;
	}

	public Integer getBidId() {
		return this.bidId;
	}

	public void setBidId(Integer bidId) {
		this.bidId = bidId;
	}

	public ServiceDetail getServiceDetail() {
		return this.serviceDetail;
	}

	public void setServiceDetail(ServiceDetail serviceDetail) {
		this.serviceDetail = serviceDetail;
	}

	public Startup getStartup() {
		return this.startup;
	}

	public void setStartup(Startup startup) {
		this.startup = startup;
	}

	public int getBidAmount() {
		return this.bidAmount;
	}

	public void setBidAmount(int bidAmount) {
		this.bidAmount = bidAmount;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getTimeRequired() {
		return this.timeRequired;
	}

	public void setTimeRequired(Date timeRequired) {
		this.timeRequired = timeRequired;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getWorkTables() {
		return this.workTables;
	}

	public void setWorkTables(Set workTables) {
		this.workTables = workTables;
	}

}
