package neu.edu.entity;
// Generated Dec 10, 2017 12:49:06 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String catergoryName;
	private Set ideas = new HashSet(0);
	private Set startups = new HashSet(0);

	public Category() {
	}

	public Category(String catergoryName) {
		this.catergoryName = catergoryName;
	}

	public Category(String catergoryName, Set ideas, Set startups) {
		this.catergoryName = catergoryName;
		this.ideas = ideas;
		this.startups = startups;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCatergoryName() {
		return this.catergoryName;
	}

	public void setCatergoryName(String catergoryName) {
		this.catergoryName = catergoryName;
	}

	public Set getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set ideas) {
		this.ideas = ideas;
	}

	public Set getStartups() {
		return this.startups;
	}

	public void setStartups(Set startups) {
		this.startups = startups;
	}

}
