package neu.edu.entity;
// Generated Dec 10, 2017 12:49:06 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Creator generated by hbm2java
 */
public class Creator implements java.io.Serializable {

	private Integer creatorId;
	private String status;
	private String reason;
	private Date lastIdeaDate;
	private Set users = new HashSet(0);
	private Set ideas = new HashSet(0);

	public Creator() {
	}

	public Creator(String status, String reason, Date lastIdeaDate, Set users, Set ideas) {
		this.status = status;
		this.reason = reason;
		this.lastIdeaDate = lastIdeaDate;
		this.users = users;
		this.ideas = ideas;
	}

	public Integer getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Date getLastIdeaDate() {
		return this.lastIdeaDate;
	}

	public void setLastIdeaDate(Date lastIdeaDate) {
		this.lastIdeaDate = lastIdeaDate;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set ideas) {
		this.ideas = ideas;
	}

}
