package neu.edu.entity;
// Generated Dec 10, 2017 12:49:06 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Idea generated by hbm2java
 */
public class Idea implements java.io.Serializable {

	private Integer ideaId;
	private Category category;
	private Creator creator;
	private String name;
	private String description;
	private int totalFund;
	private int receivedFund;
	private String status;
	private String reason;
	private Date ideaDate;
	private Set serviceDetails = new HashSet(0);
	private Set fundings = new HashSet(0);

	public Idea() {
	}

	public Idea(Category category, Creator creator, String name, String description, int totalFund, int receivedFund,
			Date ideaDate) {
		this.category = category;
		this.creator = creator;
		this.name = name;
		this.description = description;
		this.totalFund = totalFund;
		this.receivedFund = receivedFund;
		this.ideaDate = ideaDate;
	}

	public Idea(Category category, Creator creator, String name, String description, int totalFund, int receivedFund,
			String status, String reason, Date ideaDate, Set serviceDetails, Set fundings) {
		this.category = category;
		this.creator = creator;
		this.name = name;
		this.description = description;
		this.totalFund = totalFund;
		this.receivedFund = receivedFund;
		this.status = status;
		this.reason = reason;
		this.ideaDate = ideaDate;
		this.serviceDetails = serviceDetails;
		this.fundings = fundings;
	}

	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Creator getCreator() {
		return this.creator;
	}

	public void setCreator(Creator creator) {
		this.creator = creator;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getTotalFund() {
		return this.totalFund;
	}

	public void setTotalFund(int totalFund) {
		this.totalFund = totalFund;
	}

	public int getReceivedFund() {
		return this.receivedFund;
	}

	public void setReceivedFund(int receivedFund) {
		this.receivedFund = receivedFund;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Date getIdeaDate() {
		return this.ideaDate;
	}

	public void setIdeaDate(Date ideaDate) {
		this.ideaDate = ideaDate;
	}

	public Set getServiceDetails() {
		return this.serviceDetails;
	}

	public void setServiceDetails(Set serviceDetails) {
		this.serviceDetails = serviceDetails;
	}

	public Set getFundings() {
		return this.fundings;
	}

	public void setFundings(Set fundings) {
		this.fundings = fundings;
	}

}
