package neu.edu.entity;
// Generated Dec 10, 2017 12:49:06 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer personId;
	private String firstName;
	private String lastName;
	private Set users = new HashSet(0);

	public Person() {
	}

	public Person(String firstName, String lastName, Set users) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.users = users;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
