package neu.edu.entity;
// Generated Dec 10, 2017 12:06:39 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceDetail generated by hbm2java
 */
public class ServiceDetail implements java.io.Serializable {

	private Integer serviceId;
	private Idea idea;
	private int maxBidAmount;
	private String serviceDes;
	private Date serviceEndDate;
	private int amount;
	private Set bidses = new HashSet(0);
	private Set workTables = new HashSet(0);

	public ServiceDetail() {
	}

	public ServiceDetail(Idea idea, int maxBidAmount, String serviceDes, Date serviceEndDate, int amount) {
		this.idea = idea;
		this.maxBidAmount = maxBidAmount;
		this.serviceDes = serviceDes;
		this.serviceEndDate = serviceEndDate;
		this.amount = amount;
	}

	public ServiceDetail(Idea idea, int maxBidAmount, String serviceDes, Date serviceEndDate, int amount, Set bidses,
			Set workTables) {
		this.idea = idea;
		this.maxBidAmount = maxBidAmount;
		this.serviceDes = serviceDes;
		this.serviceEndDate = serviceEndDate;
		this.amount = amount;
		this.bidses = bidses;
		this.workTables = workTables;
	}

	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	public int getMaxBidAmount() {
		return this.maxBidAmount;
	}

	public void setMaxBidAmount(int maxBidAmount) {
		this.maxBidAmount = maxBidAmount;
	}

	public String getServiceDes() {
		return this.serviceDes;
	}

	public void setServiceDes(String serviceDes) {
		this.serviceDes = serviceDes;
	}

	public Date getServiceEndDate() {
		return this.serviceEndDate;
	}

	public void setServiceEndDate(Date serviceEndDate) {
		this.serviceEndDate = serviceEndDate;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Set getBidses() {
		return this.bidses;
	}

	public void setBidses(Set bidses) {
		this.bidses = bidses;
	}

	public Set getWorkTables() {
		return this.workTables;
	}

	public void setWorkTables(Set workTables) {
		this.workTables = workTables;
	}

}
