package neu.edu.entity;
// Generated Dec 10, 2017 2:05:26 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceDetail generated by hbm2java
 */
@Entity
@Table(name = "service_detail", catalog = "crowdsourcing")
public class ServiceDetail implements java.io.Serializable {

	private Integer serviceId;
	private Idea idea;
	private int maxBidAmount;
	private String serviceDes;
	private Date serviceEndDate;
	private int amount;
	private Set<Bids> bidses = new HashSet<Bids>(0);
	private Set<WorkTable> workTables = new HashSet<WorkTable>(0);

	public ServiceDetail() {
	}

	public ServiceDetail(Idea idea, int maxBidAmount, String serviceDes, Date serviceEndDate, int amount) {
		this.idea = idea;
		this.maxBidAmount = maxBidAmount;
		this.serviceDes = serviceDes;
		this.serviceEndDate = serviceEndDate;
		this.amount = amount;
	}

	public ServiceDetail(Idea idea, int maxBidAmount, String serviceDes, Date serviceEndDate, int amount,
			Set<Bids> bidses, Set<WorkTable> workTables) {
		this.idea = idea;
		this.maxBidAmount = maxBidAmount;
		this.serviceDes = serviceDes;
		this.serviceEndDate = serviceEndDate;
		this.amount = amount;
		this.bidses = bidses;
		this.workTables = workTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_id", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "max_bid_amount", nullable = false)
	public int getMaxBidAmount() {
		return this.maxBidAmount;
	}

	public void setMaxBidAmount(int maxBidAmount) {
		this.maxBidAmount = maxBidAmount;
	}

	@Column(name = "service_des", nullable = false, length = 100)
	public String getServiceDes() {
		return this.serviceDes;
	}

	public void setServiceDes(String serviceDes) {
		this.serviceDes = serviceDes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "service_end_date", nullable = false, length = 19)
	public Date getServiceEndDate() {
		return this.serviceEndDate;
	}

	public void setServiceEndDate(Date serviceEndDate) {
		this.serviceEndDate = serviceEndDate;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceDetail")
	public Set<Bids> getBidses() {
		return this.bidses;
	}

	public void setBidses(Set<Bids> bidses) {
		this.bidses = bidses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceDetail")
	public Set<WorkTable> getWorkTables() {
		return this.workTables;
	}

	public void setWorkTables(Set<WorkTable> workTables) {
		this.workTables = workTables;
	}

}
