package neu.edu.entity;
// Generated Dec 10, 2017 2:05:26 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Startup generated by hbm2java
 */
@Entity
@Table(name = "startup", catalog = "crowdsourcing")
public class Startup implements java.io.Serializable {

	private Integer startupId;
	private Category category;
	private String status;
	private String reason;
	private Set<Bids> bidses = new HashSet<Bids>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<WorkTable> workTables = new HashSet<WorkTable>(0);

	public Startup() {
	}

	public Startup(Category category) {
		this.category = category;
	}

	public Startup(Category category, String status, String reason, Set<Bids> bidses, Set<User> users,
			Set<WorkTable> workTables) {
		this.category = category;
		this.status = status;
		this.reason = reason;
		this.bidses = bidses;
		this.users = users;
		this.workTables = workTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "startup_id", unique = true, nullable = false)
	public Integer getStartupId() {
		return this.startupId;
	}

	public void setStartupId(Integer startupId) {
		this.startupId = startupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "reason", length = 500)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startup")
	public Set<Bids> getBidses() {
		return this.bidses;
	}

	public void setBidses(Set<Bids> bidses) {
		this.bidses = bidses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startup")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startup")
	public Set<WorkTable> getWorkTables() {
		return this.workTables;
	}

	public void setWorkTables(Set<WorkTable> workTables) {
		this.workTables = workTables;
	}

}
