package neu.edu.entity;
// Generated Dec 10, 2017 12:06:39 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Startup generated by hbm2java
 */
public class Startup implements java.io.Serializable {

	private Integer startupId;
	private Category category;
	private String status;
	private String reason;
	private Set bidses = new HashSet(0);
	private Set users = new HashSet(0);
	private Set workTables = new HashSet(0);

	public Startup() {
	}

	public Startup(Category category) {
		this.category = category;
	}

	public Startup(Category category, String status, String reason, Set bidses, Set users, Set workTables) {
		this.category = category;
		this.status = status;
		this.reason = reason;
		this.bidses = bidses;
		this.users = users;
		this.workTables = workTables;
	}

	public Integer getStartupId() {
		return this.startupId;
	}

	public void setStartupId(Integer startupId) {
		this.startupId = startupId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Set getBidses() {
		return this.bidses;
	}

	public void setBidses(Set bidses) {
		this.bidses = bidses;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getWorkTables() {
		return this.workTables;
	}

	public void setWorkTables(Set workTables) {
		this.workTables = workTables;
	}

}
