package neu.edu.entity;
// Generated Dec 10, 2017 12:06:39 PM by Hibernate Tools 5.2.6.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private Creator creator;
	private Funders funders;
	private Person person;
	private Startup startup;
	private String emailId;
	private String password;
	private String admin;

	public User() {
	}

	public User(String emailId, String password) {
		this.emailId = emailId;
		this.password = password;
	}

	public User(Creator creator, Funders funders, Person person, Startup startup, String emailId, String password,
			String admin) {
		this.creator = creator;
		this.funders = funders;
		this.person = person;
		this.startup = startup;
		this.emailId = emailId;
		this.password = password;
		this.admin = admin;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Creator getCreator() {
		return this.creator;
	}

	public void setCreator(Creator creator) {
		this.creator = creator;
	}

	public Funders getFunders() {
		return this.funders;
	}

	public void setFunders(Funders funders) {
		this.funders = funders;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Startup getStartup() {
		return this.startup;
	}

	public void setStartup(Startup startup) {
		this.startup = startup;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAdmin() {
		return this.admin;
	}

	public void setAdmin(String admin) {
		this.admin = admin;
	}

}
