package neu.edu.entity;
// Generated Dec 10, 2017 2:05:26 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WorkTable generated by hbm2java
 */
@Entity
@Table(name = "work_table", catalog = "crowdsourcing")
public class WorkTable implements java.io.Serializable {

	private Integer workId;
	private Bids bids;
	private ServiceDetail serviceDetail;
	private Startup startup;
	private Integer progress;
	private String description;

	public WorkTable() {
	}

	public WorkTable(Bids bids, ServiceDetail serviceDetail, Startup startup, String description) {
		this.bids = bids;
		this.serviceDetail = serviceDetail;
		this.startup = startup;
		this.description = description;
	}

	public WorkTable(Bids bids, ServiceDetail serviceDetail, Startup startup, Integer progress, String description) {
		this.bids = bids;
		this.serviceDetail = serviceDetail;
		this.startup = startup;
		this.progress = progress;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "work_id", unique = true, nullable = false)
	public Integer getWorkId() {
		return this.workId;
	}

	public void setWorkId(Integer workId) {
		this.workId = workId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bid_id", nullable = false)
	public Bids getBids() {
		return this.bids;
	}

	public void setBids(Bids bids) {
		this.bids = bids;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_id", nullable = false)
	public ServiceDetail getServiceDetail() {
		return this.serviceDetail;
	}

	public void setServiceDetail(ServiceDetail serviceDetail) {
		this.serviceDetail = serviceDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "startup_id", nullable = false)
	public Startup getStartup() {
		return this.startup;
	}

	public void setStartup(Startup startup) {
		this.startup = startup;
	}

	@Column(name = "progress")
	public Integer getProgress() {
		return this.progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
