package neu.edu.entity;
// Generated Dec 10, 2017 12:06:39 PM by Hibernate Tools 5.2.6.Final

/**
 * WorkTable generated by hbm2java
 */
public class WorkTable implements java.io.Serializable {

	private Integer workId;
	private Bids bids;
	private ServiceDetail serviceDetail;
	private Startup startup;
	private Integer progress;
	private String description;

	public WorkTable() {
	}

	public WorkTable(Bids bids, ServiceDetail serviceDetail, Startup startup, String description) {
		this.bids = bids;
		this.serviceDetail = serviceDetail;
		this.startup = startup;
		this.description = description;
	}

	public WorkTable(Bids bids, ServiceDetail serviceDetail, Startup startup, Integer progress, String description) {
		this.bids = bids;
		this.serviceDetail = serviceDetail;
		this.startup = startup;
		this.progress = progress;
		this.description = description;
	}

	public Integer getWorkId() {
		return this.workId;
	}

	public void setWorkId(Integer workId) {
		this.workId = workId;
	}

	public Bids getBids() {
		return this.bids;
	}

	public void setBids(Bids bids) {
		this.bids = bids;
	}

	public ServiceDetail getServiceDetail() {
		return this.serviceDetail;
	}

	public void setServiceDetail(ServiceDetail serviceDetail) {
		this.serviceDetail = serviceDetail;
	}

	public Startup getStartup() {
		return this.startup;
	}

	public void setStartup(Startup startup) {
		this.startup = startup;
	}

	public Integer getProgress() {
		return this.progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
